name: Auto-update products.json

on:
  push:
    paths:
      - "product-images/*"

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git Config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Generate products.json
      run: |
        IMAGES_DIR="product-images"
        JSON_FILE="products.json"
        echo "[" > $JSON_FILE
        for file in $IMAGES_DIR/*; do
          if [[ $file == *.jpg || $file == *.png ]]; then
            filename=$(basename -- "$file")
            echo "\"$filename\"," >> $JSON_FILE
          fi
        done
        sed -i '$ s/,$//' $JSON_FILE # Remove trailing comma from last item
        echo "]" >> $JSON_FILE

    - name: Commit Changes
      run: |
        git add products.json
        git commit -m "Auto-update products.json" || echo "No changes to commit"

    - name: Pull Latest Changes
      run: git pull origin main --rebase

    - name: Push Changes
      run: |
        git push origin main
