name: Update Products JSON

on:
  push:
    paths:
      - product-images/**

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate products.json
      run: |
        echo "[" > products.json
        for file in product-images/*; do
          filename=$(basename "$file")
          echo "  \"$filename\"," >> products.json
        done
        sed -i '$ s/,$//' products.json # Remove last comma
        echo "]" >> products.json

    - name: Commit Updated JSON
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add products.json
        git commit -m "Auto-update products.json"
        git push
